### ISSUE TITLE
Need help installing 

### ISSUE THREAD

**Issue by eldiosdelpit0** [aekaisato/cr-force-hardsub#2]
Hi, I'm new to this type of stuff and I'm having trouble figuring out how to use this extension you made. Any help would be greatly appreciated.

**Comment by aekaisato** [comment]
Sure, let me know if these instructions work for you.

1. Download and install the extension from the Firefox Add-ons Store (extension is currently Firefox only): https://addons.mozilla.org/en-US/firefox/addon/spicyroll/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
2. Go to extension settings (right click on extension icon, click "Manage Extension"
3. Go to permissions tab
4. Enable both site permissions

**Comment by eldiosdelpit0** [comment]
You're a life saver 🙏🙏🙏🙏🙏🙏 TYSM!
