### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Vincentevil** [aekaisato/cr-force-hardsub#3]
Hi, I just tried your Firefox extension but I'm afraid it doesn't work for me...
Could you help me out?

**Comment by aekaisato** [comment]
Hi, can you follow the instructions [here](https://github.com/aekaisato/cr-force-hardsub/issues/2#issuecomment-2150176880) and see if it works from there?

**Comment by aekaisato** [comment]
Actually it seems like Crunchyroll changed the URL scheme for playback details. Will push a fix as soon as I can.

**Comment by aekaisato** [comment]
Fixed with https://github.com/aekaisato/cr-force-hardsub/commit/c556a313f9a8d4e54e500c91945f4a4a11638f16

**Comment by Vincentevil** [comment]
Thank you for responding so quickly. It's working wonderfully!
